### PR TITLE
Update README due the migration to Eclipse

### PR DESCRIPTION
**Pull request by twebermartins**

### CODE REVIEW

**Comment by sebbader-sap** [comment]
@twebermartins is this PR still needed or can we close it?

**Comment by twebermartins** [comment]
Thanks, @sebbader-sap! If possible, could you please merge! It is about updating the readme so that the community knows that the development and maintaince is now at Eclipse Foundation.

**Comment by sebbader** [comment]
True, I was just in 'closing mode' :-).

**Comment by twebermartins** [comment]
Thanks!

**Pull request merged**
